### transaction from John Doe to Jane Doe
POST http://localhost:8081/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "546fbcb8-180a-4dd9-b36b-16304cf3e60a",
    "account_id_to": "ca88c60a-6092-49a7-9d58-6bd16fbc30d2",
    "amount": 100.99
}


### transaction from Jane Doe to John Doe
POST http://localhost:8081/transactions HTTP/1.1
Content-Type: application/json

{
    "account_id_from": "ca88c60a-6092-49a7-9d58-6bd16fbc30d2",
    "account_id_to": "546fbcb8-180a-4dd9-b36b-16304cf3e60a",
    "amount": 50.90
}
